name: Fill book info

on:
  schedule:
    - cron: "* * * * *"
  workflow_dispatch: {}

jobs:
  fill-book-info:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: node fill_book_info.mjs
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          KAKAO_REST_API_KEY: ${{ secrets.KAKAO_REST_API_KEY }}
